SELECT
  v_church_member.id_church,
  v_church_member.church_name,
  v_church_member.due,
  v_church_member.paid
FROM
  v_church_member
UNION
ALL
SELECT
  v_church_apprentice.id_church,
  v_church_apprentice.church_name,
  v_church_apprentice.due,
  v_church_apprentice.paid
FROM
  v_church_apprentice
UNION
ALL
SELECT
  v_church_leader.id_church,
  v_church_leader.church_name,
  v_church_leader.due,
  v_church_leader.paid
FROM
  v_church_leader;